import {
  type DocumentTemplate,
  type TemplateField,
} from "@/types/document-templates";

function field(
  input: Omit<TemplateField, "sortOrder"> & { sortOrder?: number },
): TemplateField {
  return {
    sortOrder: input.sortOrder ?? 0,
    ...input,
  };
}

const commonReadonlyFields: TemplateField[] = [
  field({
    key: "patient_full_name",
    label: "Pacienta vārds, uzvārds",
    placeholder: "{{patient_full_name}}",
    source: "patient",
    required: true,
    editable: false,
    status: "auto",
    inputType: "text",
    sortOrder: 10,
  }),
  field({
    key: "patient_personal_code",
    label: "Personas kods",
    placeholder: "{{patient_personal_code}}",
    source: "patient",
    required: true,
    editable: false,
    status: "auto",
    inputType: "text",
    sortOrder: 20,
  }),
  field({
    key: "patient_birth_date",
    label: "Dzimšanas datums",
    placeholder: "{{patient_birth_date}}",
    source: "patient",
    required: true,
    editable: false,
    status: "auto",
    inputType: "date",
    sortOrder: 30,
  }),
  field({
    key: "patient_age",
    label: "Vecums",
    placeholder: "{{patient_age}}",
    source: "patient",
    required: true,
    editable: false,
    status: "auto",
    inputType: "text",
    sortOrder: 40,
  }),
  field({
    key: "patient_gender",
    label: "Dzimums",
    placeholder: "{{patient_gender}}",
    source: "patient",
    required: true,
    editable: false,
    status: "auto",
    inputType: "text",
    sortOrder: 50,
  }),
  field({
    key: "doctor_name",
    label: "Ārsta vārds",
    placeholder: "{{doctor_name}}",
    source: "doctor",
    required: true,
    editable: false,
    status: "auto",
    inputType: "text",
    sortOrder: 60,
  }),
  field({
    key: "practice_name",
    label: "Prakses nosaukums",
    placeholder: "{{practice_name}}",
    source: "practice",
    required: true,
    editable: false,
    status: "auto",
    inputType: "text",
    sortOrder: 70,
  }),
  field({
    key: "practice_registration_number",
    label: "Prakses reģistrācijas numurs",
    placeholder: "{{practice_registration_number}}",
    source: "practice",
    required: true,
    editable: false,
    status: "auto",
    inputType: "text",
    sortOrder: 80,
  }),
  field({
    key: "today_date",
    label: "Sagatavošanas datums",
    placeholder: "{{today_date}}",
    source: "system",
    required: true,
    editable: false,
    status: "auto",
    inputType: "date",
    sortOrder: 90,
  }),
];

const vdeavkReferralReasonOptions = [
  "Prognozējamās invaliditātes ekspertīzei",
  "Invaliditātes un darbspēju ekspertīzei",
  "Īpašas kopšanas medicīnisko indikāciju ekspertīzei",
  "Vieglā automobiļa speciālās pielāgošanas un pabalsta saņemšanas transporta izdevumu kompensēšanai medicīnisko indikāciju ekspertīzei",
  "Pavadoņa pakalpojuma saņemšanas ekspertīzei",
  "Atzinuma sniegšanai par darbnespējas lapas pagarināšanu pārejošas darbnespējas periodā",
  "Cits iemesls",
];

const vdeavkReadonlyFields: TemplateField[] = [
  field({
    key: "practice_name",
    label: "\u0100rstniec\u012bbas iest\u0101des nosaukums",
    placeholder: "{{practice_name}}",
    source: "practice",
    required: true,
    editable: false,
    status: "auto",
    inputType: "text",
    sortOrder: 10,
  }),
  field({
    key: "practice_registration_number",
    label: "Kods",
    placeholder: "{{practice_registration_number}}",
    source: "practice",
    required: true,
    editable: false,
    status: "auto",
    inputType: "text",
    sortOrder: 20,
  }),
  field({
    key: "patient_full_name",
    label: "1. Pacienta v\u0101rds, uzv\u0101rds",
    placeholder: "{{patient_full_name}}",
    source: "patient",
    required: true,
    editable: false,
    status: "auto",
    inputType: "text",
    sortOrder: 30,
  }),
  field({
    key: "patient_personal_code",
    label: "2. Personas kods",
    placeholder: "{{patient_personal_code}}",
    source: "patient",
    required: true,
    editable: false,
    status: "auto",
    inputType: "text",
    sortOrder: 40,
  }),
  field({
    key: "patient_gender_vdeavk",
    label: "3. Dzimums",
    placeholder: "{{patient_gender_vdeavk}}",
    source: "patient",
    required: true,
    editable: false,
    status: "auto",
    inputType: "text",
    sortOrder: 50,
  }),
  field({
    key: "today_date",
    label: "10. Nos\u016bt\u012bjuma sagatavo\u0161anas datums (dd.mm.gggg.)",
    placeholder: "{{today_date}}",
    source: "system",
    required: true,
    editable: false,
    status: "auto",
    inputType: "date",
    sortOrder: 120,
  }),
  field({
    key: "doctor_name",
    label: "11. Nos\u016bt\u012bjumu sagatavoja (\u0101rsta v\u0101rds, uzv\u0101rds)",
    placeholder: "{{doctor_name}}",
    source: "doctor",
    required: true,
    editable: false,
    status: "auto",
    inputType: "text",
    sortOrder: 130,
  }),
];

export const documentTemplates: DocumentTemplate[] = [
  {
    id: "vdeavk_work_ability_referral",
    title: "Darba nesp\u0113jas ekspert\u012bzes nos\u016bt\u012bjums Nr. 088/u",
    description: "Nos\u016bt\u012bjuma melnraksts darba nesp\u0113jas ekspert\u012bzei.",
    category: "nosutijums",
    templateFilePath: "/templates/vdeavk_work_ability_referral.docx",
    outputFileNamePattern:
      "{{patient_last_name}}_{{patient_first_name}}_VDEAVK_nosutijums.docx",
    fields: [
      ...vdeavkReadonlyFields,
      field({
        key: "active_diagnoses",
        label:
          "4. Diagnozes, nos\u016btot pacientu uz invalidit\u0101tes un darbsp\u0113ju ekspert\u012bzi",
        placeholder: "{{active_diagnoses}}",
        source: "suggested",
        required: true,
        editable: true,
        status: "needs_confirmation",
        inputType: "textarea",
        sortOrder: 60,
      }),
      field({
        key: "doctor_fill_health_description",
        label:
          "5. Vesel\u012bbas trauc\u0113jumu apraksts, ieskaitot anamn\u0113zi, veikto \u0101rst\u0113\u0161anu, t\u0101s rezult\u0101tus, k\u0101 ar\u012b paredzamo \u0101rst\u0113\u0161anu un prognozi, ja t\u0101da iesp\u0113jama",
        placeholder: "{{doctor_fill_health_description}}",
        source: "doctor",
        required: true,
        editable: true,
        status: "doctor_required",
        inputType: "textarea",
        sortOrder: 70,
      }),
      field({
        key: "lab_results",
        label:
          "6. Izmekl\u0113jumi un konsultantu atzinumi, kas pamato 4. punkt\u0101 min\u0113t\u0101s diagnozes",
        placeholder: "{{lab_results}}",
        source: "suggested",
        required: true,
        editable: true,
        status: "needs_confirmation",
        inputType: "textarea",
        sortOrder: 80,
      }),
      field({
        key: "sick_leave_periods",
        label:
          "7. P\u0101rejo\u0161\u0101 darbnesp\u0113ja (nor\u0101d\u012bt periodu p\u0113d\u0113jo 6 m\u0113ne\u0161u laik\u0101 pamatslim\u012bbas d\u0113\u013c)",
        placeholder: "{{sick_leave_periods}}",
        source: "suggested",
        required: true,
        editable: true,
        status: "needs_confirmation",
        inputType: "textarea",
        sortOrder: 90,
      }),
      field({
        key: "doctor_fill_functional_limitations",
        label:
          "8. Fizik\u0101l\u0101s/psihisk\u0101s izmekl\u0113\u0161anas dati, \u0137erme\u0146a funkciju trauc\u0113jumu un aktivit\u0101\u0161u ierobe\u017eojuma nov\u0113rt\u0113jums",
        placeholder: "{{doctor_fill_functional_limitations}}",
        source: "doctor",
        required: true,
        editable: true,
        status: "doctor_required",
        inputType: "textarea",
        sortOrder: 100,
      }),
      field({
        key: "doctor_fill_referral_reason",
        label: "9. Nos\u016bt\u012bjuma sagatavo\u0161anas iemesls",
        placeholder: "{{doctor_fill_referral_reason}}",
        source: "doctor",
        required: true,
        editable: true,
        status: "doctor_required",
        inputType: "checkbox",
        options: vdeavkReferralReasonOptions,
        sortOrder: 110,
      }),
      field({
        key: "doctor_fill_attached_documents",
        label: "12. Pievienoto dokumentu kopiju saraksts",
        placeholder: "{{doctor_fill_attached_documents}}",
        source: "doctor",
        required: false,
        editable: true,
        status: "doctor_required",
        inputType: "textarea",
        sortOrder: 140,
      }),
    ],
  },
  {
    id: "vaccination_pass_entries",
    title: "Vakcinācijas pases ieraksti",
    description: "Vakcinācijas vēstures ierakstu sagatave.",
    category: "vakcinacija",
    templateFilePath: "/templates/vaccination_pass_entries.docx",
    outputFileNamePattern:
      "{{patient_last_name}}_{{patient_first_name}}_vakcinacijas_pase.docx",
    fields: [
      ...commonReadonlyFields,
      field({
        key: "vaccination_history",
        label: "Vakcinācijas vēsture",
        placeholder: "{{vaccination_history}}",
        source: "suggested",
        required: true,
        editable: true,
        status: "needs_confirmation",
        inputType: "textarea",
        sortOrder: 100,
      }),
      field({
        key: "doctor_fill_additional_notes",
        label: "Papildu piezīmes",
        placeholder: "{{doctor_fill_additional_notes}}",
        source: "doctor",
        required: false,
        editable: true,
        status: "doctor_required",
        inputType: "textarea",
        sortOrder: 110,
      }),
    ],
  },
  {
    id: "ambulatory_extract_027u",
    title: "Izraksts no ambulatorā pacienta kartes (Veidlapa Nr. 027/u)",
    description: "Pacienta ambulatorās ārstēšanas kopsavilkums.",
    category: "izraksts",
    templateFilePath: "/templates/ambulatory_extract_027u.docx",
    outputFileNamePattern:
      "{{patient_last_name}}_{{patient_first_name}}_027u_izraksts.docx",
    fields: [
      ...commonReadonlyFields,
      field({
        key: "diagnosis_summary",
        label: "Diagnožu kopsavilkums",
        placeholder: "{{diagnosis_summary}}",
        source: "suggested",
        required: true,
        editable: true,
        status: "needs_confirmation",
        inputType: "textarea",
        sortOrder: 100,
      }),
      field({
        key: "medications",
        label: "Medikamenti",
        placeholder: "{{medications}}",
        source: "suggested",
        required: false,
        editable: true,
        status: "needs_confirmation",
        inputType: "textarea",
        sortOrder: 110,
      }),
      field({
        key: "visit_summary",
        label: "Vizītes kopsavilkums",
        placeholder: "{{visit_summary}}",
        source: "suggested",
        required: true,
        editable: true,
        status: "needs_confirmation",
        inputType: "textarea",
        sortOrder: 120,
      }),
      field({
        key: "doctor_fill_reason",
        label: "Nosūtīšanas iemesls",
        placeholder: "{{doctor_fill_reason}}",
        source: "doctor",
        required: true,
        editable: true,
        status: "doctor_required",
        inputType: "textarea",
        sortOrder: 130,
      }),
    ],
  },
  {
    id: "driver_medical_certificate",
    title: "Autovadītāju medicīniskā izziņa",
    description: "Izziņas sagatave transportlīdzekļa vadītājam.",
    category: "izzina",
    templateFilePath: "/templates/driver_medical_certificate.docx",
    outputFileNamePattern:
      "{{patient_last_name}}_{{patient_first_name}}_autovaditaja_izzina.docx",
    fields: [
      ...commonReadonlyFields,
      field({
        key: "active_diagnoses",
        label: "Aktīvās diagnozes",
        placeholder: "{{active_diagnoses}}",
        source: "suggested",
        required: true,
        editable: true,
        status: "needs_confirmation",
        inputType: "textarea",
        sortOrder: 100,
      }),
      field({
        key: "doctor_fill_recommendations",
        label: "Ārsta secinājums",
        placeholder: "{{doctor_fill_recommendations}}",
        source: "doctor",
        required: true,
        editable: true,
        status: "doctor_required",
        inputType: "textarea",
        sortOrder: 110,
      }),
    ],
  },
  {
    id: "weapons_possession_certificate",
    title: "Izziņa ieroču glabāšanai un nēsāšanai",
    description: "Izziņas sagatave veselības atbilstībai.",
    category: "izzina",
    templateFilePath: "/templates/weapons_possession_certificate.docx",
    outputFileNamePattern:
      "{{patient_last_name}}_{{patient_first_name}}_ierocu_izzina.docx",
    fields: [
      ...commonReadonlyFields,
      field({
        key: "active_diagnoses",
        label: "Aktīvās diagnozes",
        placeholder: "{{active_diagnoses}}",
        source: "suggested",
        required: true,
        editable: true,
        status: "needs_confirmation",
        inputType: "textarea",
        sortOrder: 100,
      }),
      field({
        key: "doctor_fill_additional_notes",
        label: "Ārsta atzinums",
        placeholder: "{{doctor_fill_additional_notes}}",
        source: "doctor",
        required: true,
        editable: true,
        status: "doctor_required",
        inputType: "textarea",
        sortOrder: 110,
      }),
    ],
  },
  {
    id: "sports_pool_certificate",
    title: "Izziņa sporta sekcijai vai baseinam",
    description: "Izziņas sagatave fiziskās slodzes pieļaujamībai.",
    category: "izzina",
    templateFilePath: "/templates/sports_pool_certificate.docx",
    outputFileNamePattern:
      "{{patient_last_name}}_{{patient_first_name}}_sporta_izzina.docx",
    fields: [
      ...commonReadonlyFields,
      field({
        key: "active_diagnoses",
        label: "Aktīvās diagnozes",
        placeholder: "{{active_diagnoses}}",
        source: "suggested",
        required: false,
        editable: true,
        status: "needs_confirmation",
        inputType: "textarea",
        sortOrder: 100,
      }),
      field({
        key: "doctor_fill_recommendations",
        label: "Pieļaujamā slodze",
        placeholder: "{{doctor_fill_recommendations}}",
        source: "doctor",
        required: true,
        editable: true,
        status: "doctor_required",
        inputType: "textarea",
        sortOrder: 110,
      }),
    ],
  },
  {
    id: "education_excuse_certificate",
    title: "Attaisnojoša izziņa izglītības iestādei",
    description: "Prombūtnes vai sporta atbrīvojuma sagatave.",
    category: "izzina",
    templateFilePath: "/templates/education_excuse_certificate.docx",
    outputFileNamePattern:
      "{{patient_last_name}}_{{patient_first_name}}_skolas_izzina.docx",
    fields: [
      ...commonReadonlyFields,
      field({
        key: "visit_summary",
        label: "Vizītes kopsavilkums",
        placeholder: "{{visit_summary}}",
        source: "suggested",
        required: true,
        editable: true,
        status: "needs_confirmation",
        inputType: "textarea",
        sortOrder: 100,
      }),
      field({
        key: "doctor_fill_reason",
        label: "Prombūtnes pamatojums",
        placeholder: "{{doctor_fill_reason}}",
        source: "doctor",
        required: true,
        editable: true,
        status: "doctor_required",
        inputType: "textarea",
        sortOrder: 110,
      }),
    ],
  },
  {
    id: "mandatory_health_check_ovp",
    title: "Obligātās veselības pārbaudes karte — OVP",
    description: "OVP melnraksts darba vides riska izvērtējumam.",
    category: "ovp",
    templateFilePath: "/templates/mandatory_health_check_ovp.docx",
    outputFileNamePattern:
      "{{patient_last_name}}_{{patient_first_name}}_OVP_karte.docx",
    fields: [
      ...commonReadonlyFields,
      field({
        key: "active_diagnoses",
        label: "Aktīvās diagnozes",
        placeholder: "{{active_diagnoses}}",
        source: "suggested",
        required: true,
        editable: true,
        status: "needs_confirmation",
        inputType: "textarea",
        sortOrder: 100,
      }),
      field({
        key: "doctor_fill_reason",
        label: "Darba vides riska faktori",
        placeholder: "{{doctor_fill_reason}}",
        source: "doctor",
        required: true,
        editable: true,
        status: "doctor_required",
        inputType: "textarea",
        sortOrder: 110,
      }),
      field({
        key: "doctor_fill_recommendations",
        label: "Atzinums par piemērotību darbam",
        placeholder: "{{doctor_fill_recommendations}}",
        source: "doctor",
        required: true,
        editable: true,
        status: "doctor_required",
        inputType: "textarea",
        sortOrder: 120,
      }),
    ],
  },
];

export const documentTemplateMap = Object.fromEntries(
  documentTemplates.map((template) => [template.id, template]),
);
